from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
        path('',views.index),
        path('stock',views.stock),
        path('sales',views.sales),
        path('sales-bill',views.salesbill),
        path('purchase-bill',views.purchasebill),
        path('saving',views.saving),
        path('credit',views.credit),
        path('expense',views.expense),
    
        path('tb',views.transportbill),
        path('report',views.report),
        path('setting',views.setting),
        path('search',views.search),
        path('searchsb',views.searchsb),
        path('searchpb',views.searchpb),
        path('searchsale',views.searchsale),
        path('searchsales<str:product>',views.searchsales),
        path('searchcredit',views.searchcredit),
        path('searchsave',views.searchsaving),
        path('<int:obj>',views.update),
        path('updatecredit<int:obj>',views.update),
        path('save',views.saving),
        path('billtemplate',views.billtemplate),
        path('searchreport',views.searchreport),
        path('billtemplates',views.billtemplates),
        path('purchasebilltemplates',views.purchasebilltemplates),
        path('showbill<int:idd>',views.showbilltemplates),
        path('editbill<int:idd>',views.editbilltemplates),
        path('editbills<int:idd>',views.editbillstemplates),
        path('updatebill<int:idd>',views.updatebill),
        path('updatebills<int:idd>',views.updatepbill),
        path('purchasebilltemplate',views.purchasebilltemplate),
        path('viewbill<int:idd>',views.viewbill),
        path('addexpense',views.expense),
        path('searchexpense',views.searchexpense),
        #for ordering:
        path('datei',views.purchasebilldate),
        path('dated',views.purchasebilldated),
        path('cd',views.purchasebillcd),
        path('ci',views.purchasebillci),
        path('paidi',views.purchasebillp),
        path('paidd',views.purchasebilld),
        #for ordering ofstock:
        path("productdescenedingorder",views.stockpd),   
        path("productincreasingorder",views.stockpi), 
        path("quantityincreasingorder",views.stockqi),   
        path("quantitydecreasingorder",views.stockqd), 
        path("leftquantityincreasingorder",views.stocklqi),   
        path("leftquantitydecreasingorder",views.stocklqd), 
        path("cpincreasingorder",views.stockcpi),   
        path("cpdecreasingorder",views.stockcpd), 
        path("spincreasingorder",views.stockspi),   
        path("spdecreasingorder",views.stockspd), 
        #for ordering of sales
        path('datedescendingorder',views.saledd),
        path('dateincreasingorder',views.saledi),
        path('cssalesd',views.salecd),
        path('cssalesi',views.saleci),
        path("productdescenedingordersales",views.salepd),   
        path("productincreasingordersales",views.salepi), 
        path("quantitydescenedingordersales",views.saleqd),   
        path("quantityincreasingordersales",views.saleqi), 
        path("ratedescenedingordersales",views.salerd),   
        path("rateincreasingordersales",views.saleri), 
        path("discountdescenedingordersales",views.saledid),   
        path("discountincreasingordersales",views.saledii), 
        path("totaldescenedingordersales",views.saletd),   
        path("totalincreasingordersales",views.saleti), 
        path("paiddescenedingordersales",views.salepad),   
        path("paidincreasingordersales",views.salepai),
        path("remaindescenedingordersales",views.salered),   
        path("remainincreasingordersales",views.salerei), 
        #for ordering of salesbill
        path('decreasedatesale',views.ddsb),
        path('increasedatesale',views.idsb),
        path('decreasecssale',views.dcsb),
        path('increasecssale',views.icsb),
        path('decreasepsale',views.dpsb),
        path('increasepsale',views.ipsb),
        # for ordering of saving
        path('decreasedatesave',views.savedd),
        path('increasedatesave',views.saveid),
        path('decreasefsave',views.savedf),
        path('increasefsave',views.savefi),
        path('decreaseamountsave',views.saveda),
        path('increaseamountsave',views.saveia),
        # for ordering of expenses
        path('decreasedatee',views.edd),
        path('increasedatee',views.eid),
        path('decreasefe',views.edf),
        path('increasefe',views.efi),
        path('decreaseamounte',views.eda),
        path('increaseamounte',views.eia),
        #for url
        path('creditincrease<str:factor>',views.creditincrease),
        path('creditdecrease<str:factors>',views.creditdecrease),
        path('excelstock',views.stockexcel),





    
    ]
