# Generated by Django 3.2.8 on 2021-10-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=255)),
                ('Total', models.CharField(max_length=255)),
                ('Left', models.CharField(max_length=255)),
                ('Cost', models.CharField(max_length=255)),
                ('Sold', models.CharField(max_length=255)),
            ],
        ),
    ]
