# Generated by Django 3.2.8 on 2021-11-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_salesbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesbillitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Customer_name', models.CharField(max_length=255)),
                ('Customer_phone', models.CharField(max_length=255)),
                ('Customer_address', models.CharField(max_length=255)),
                ('Product', models.CharField(max_length=255)),
                ('Quantity', models.CharField(max_length=255)),
                ('Rate', models.CharField(max_length=255)),
                ('Discount', models.CharField(max_length=255)),
                ('Total', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-Date',),
            },
        ),
        migrations.AlterModelOptions(
            name='salesbill',
            options={'ordering': ('-Date',)},
        ),
    ]
