# Generated by Django 3.2.8 on 2021-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211110_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchasebill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Company_name', models.CharField(max_length=255)),
                ('Pan', models.CharField(max_length=255)),
                ('Customer_phone', models.CharField(max_length=255)),
                ('Customer_address', models.CharField(max_length=255)),
                ('Vat', models.CharField(max_length=255)),
                ('Paid', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-Date',),
            },
        ),
    ]
