# Generated by Django 3.2.8 on 2021-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_purchasebillitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Purpose', models.CharField(max_length=255)),
                ('Amount', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-Date',),
            },
        ),
    ]
