# Generated by Django 3.2.8 on 2021-11-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Cost',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Left',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Sold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Total',
            field=models.IntegerField(),
        ),
    ]
