# Generated by Django 3.2.8 on 2021-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211113_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Cost',
            field=models.IntegerField(),
        ),
    ]
