# Generated by Django 3.2.8 on 2021-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211113_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
