# Generated by Django 3.2.8 on 2021-11-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_credit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
