# Generated by Django 3.2.8 on 2021-11-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasebillitems',
            name='Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salesbillitems',
            name='Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saving',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
