# Generated by Django 3.2.8 on 2021-11-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211114_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbillitems',
            name='Product',
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='Paid',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='Vat',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='purchasebillitems',
            name='Discount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='purchasebillitems',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasebillitems',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='purchasebillitems',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='salesbillitems',
            name='Discount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='salesbillitems',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesbillitems',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='salesbillitems',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
