# Generated by Django 3.2.8 on 2021-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211114_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbillitems',
            name='Product',
            field=models.CharField(default='motul', max_length=255),
            preserve_default=False,
        ),
    ]
